import{a as f,S as v,i as m}from"./assets/vendor-DOgVoBmD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g=({webformatURL:s,largeImageURL:t,tags:o,likes:a,views:e,comments:r,downloads:i})=>`
    <a href="${t}" class="gallery__item">
    <img src="${s}" alt="${o}" class="gallery__image" />
    <div class="info">
  <p class="info-item"><b>Likes</b> ${a}</p>
  <p class="info-item"><b>Views</b> ${e}</p>
  <p class="info-item"><b>Comments</b> ${r}</p>
  <p class="info-item"><b>Downloads</b> ${i}</p>
  </div>
  </a>
  `;f.defaults.baseURL="https://pixabay.com/api/";const y=(s,t)=>{const o={params:{key:"45517792-9e921d102392e39380fbae016",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}};return f.get("",o)},c=document.querySelector(".js-search-form"),l=document.querySelector(".js-gallery"),u=document.querySelector(".js-load-more"),p=document.createElement("div");p.classList.add("loading-indicator","hidden");document.body.appendChild(p);let n=1,d="",b=0;const L=new v(".js-gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.7});function w(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}const E=async s=>{try{if(s.preventDefault(),d=c.elements.user_query.value.trim(),!d){m.warning({message:"Please enter a search query.",position:"topRight"});return}w(),n=1;const t=await y(d,n);if(t.data.total===0){m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),u.classList.add("is-hidden"),l.innerHTML="",c.reset(),h();return}const o=t.data.hits.map(e=>g(e)).join("");l.innerHTML=o,b=l.querySelector("a").getBoundingClientRect().height,u.classList.remove("is-hidden"),L.refresh()}catch(t){console.log(t)}finally{h(),c.reset()}},P=async s=>{try{n++;const t=await y(d,n),o=t.data.hits.map(e=>g(e)).join("");l.insertAdjacentHTML("beforeend",o),L.refresh(),window.scrollBy({top:b*2,behavior:"smooth"});const a=Math.ceil(t.data.totalHits/t.data.hits.length);n>=a&&(u.classList.add("is-hidden"),m.error({message:"We are sorry, but you have reached the end of search results.",position:"topRight"}))}catch(t){console.log(t)}};c.addEventListener("submit",E);u.addEventListener("click",P);
//# sourceMappingURL=index.js.map
