import{a as m,i as g,S as y}from"./assets/vendor-DOgVoBmD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const f=({webformatURL:r,largeImageURL:t,tags:a,likes:s,views:e,comments:o,downloads:i})=>`
    <a href="${t}" class="gallery__item">
    <img src="${r}" alt="${a}" class="gallery__image" />
    <div class="info">
  <p class="info-item"><b>Likes</b> ${s}</p>
  <p class="info-item"><b>Views</b> ${e}</p>
  <p class="info-item"><b>Comments</b> ${o}</p>
  <p class="info-item"><b>Downloads</b> ${i}</p>
  </div>
  </a>
  `;m.defaults.baseURL="https://pixabay.com/api/";const b=(r,t)=>{const a={params:{key:"45517792-9e921d102392e39380fbae016",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}};return m.get("",a)},l=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),d=document.querySelector(".js-load-more"),p=document.createElement("div");p.classList.add("loading-indicator","hidden");document.body.appendChild(p);let n=1,u="",L=0;function v(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}const w=async r=>{try{r.preventDefault(),u=l.elements.user_query.value.trim(),v(),n=1;const t=await b(u,n);if(t.data.total===0){g.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d.classList.add("is-hidden"),c.innerHTML="",l.reset(),h();return}const a=t.data.hits.map(o=>f(o)).join("");c.innerHTML=a,L=c.querySelector("a").getBoundingClientRect().height,d.classList.remove("is-hidden"),new y(".js-gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.7}).refresh()}catch(t){console.log(t)}finally{h(),l.reset()}},E=async r=>{try{n++;const t=await b(u,n),a=t.data.hits.map(o=>f(o)).join("");c.insertAdjacentHTML("beforeend",a),new y(".js-gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.7}).refresh(),window.scrollBy({top:L*2,behavior:"smooth"});const e=Math.ceil(t.data.totalHits/t.data.hits.length);n>=e&&(d.classList.add("is-hidden"),g.error({message:"We are sorry, but you have reached the end of search results.",position:"topRight"}))}catch(t){console.log(t)}};l.addEventListener("submit",w);d.addEventListener("click",E);
//# sourceMappingURL=index.js.map
