import{a as f,S,i as m}from"./assets/vendor-DOgVoBmD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g=({webformatURL:s,largeImageURL:t,tags:o,likes:a,views:e,comments:r,downloads:i})=>`
    <a href="${t}" class="gallery__item">
    <img src="${s}" alt="${o}" class="gallery__image" />
    <div class="info">
  <p class="info-item"><b>Likes</b> ${a}</p>
  <p class="info-item"><b>Views</b> ${e}</p>
  <p class="info-item"><b>Comments</b> ${r}</p>
  <p class="info-item"><b>Downloads</b> ${i}</p>
  </div>
  </a>
  `;f.defaults.baseURL="https://pixabay.com/api/";const y=(s,t)=>{const o={params:{key:"45517792-9e921d102392e39380fbae016",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}};return f.get("",o)},l=document.querySelector(".js-search-form"),n=document.querySelector(".js-gallery"),d=document.querySelector(".js-load-more"),p=document.createElement("div");p.classList.add("loading-indicator","hidden");document.body.appendChild(p);let u=1,c="",b=0;const L=new S(".js-gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.7});function v(){p.classList.remove("hidden")}function h(){p.classList.add("hidden")}const q=async s=>{try{if(s.preventDefault(),c=l.elements.user_query.value.trim(),!c){m.warning({message:"Please enter a search query.",position:"topRight"});return}v(),u=1;const t=await y(c,u);if(t.data.total===0){m.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d.classList.add("is-hidden"),n.innerHTML="",l.reset(),h();return}const o=t.data.hits.map(e=>g(e)).join("");n.innerHTML=o,b=n.querySelector("a").getBoundingClientRect().height,d.classList.remove("is-hidden"),L.refresh()}catch(t){console.log(t)}finally{h(),l.reset()}},w=async s=>{try{u++,v();const t=await y(c,u),o=t.data.total,a=n.querySelectorAll("a").length,e=t.data.hits.map(r=>g(r)).join("");n.insertAdjacentHTML("beforeend",e),L.refresh(),a+t.data.hits.length>=o&&(d.classList.add("is-hidden"),m.error({message:"We are sorry, but you have reached the end of search results.",position:"topRight"})),window.scrollBy({top:b*2,behavior:"smooth"})}catch(t){console.log(t)}finally{h()}};l.addEventListener("submit",q);d.addEventListener("click",w);
//# sourceMappingURL=index.js.map
